rockstarmvc/Models/ErrorViewModel.cs
using System;

namespace rockstarmvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

rockstarmvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using rockstarmvc.Models;

namespace rockstarmvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

rockstarmvc/Controllers/RockStarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using rockstarmvc.Models;

//using System.Net.Http;
//using System.Net.Http.Headers;
//using System.Text;
using System.Net;
using System.IO;
using System.Text;

namespace rockstarmvc.Controllers
{
    public class RockStarController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public RockStarController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Faith()
        {
            return View();
        }

        public IActionResult Faith2()
        {
            return View();
        }

        public IActionResult Faith3()
        {
            // var client = new HttpClient();

            // // Send a request to fetch data.
            // string requestAddress = "http://localhost:5000/rockstar/faith";
            // var request = new HttpRequestMessage(HttpMethod.Get, requestAddress);
            // var response = client.(request);
            // return response;

            var url = "http://localhost:5000/rockstar/faith";
            var request = WebRequest.CreateHttp(url);
            request.Method = "GET";

            using (var response = (HttpWebResponse)request.GetResponse())
            {
                // Get the stream associated with the response
                using (var responseStream = response.GetResponseStream())
                {
                    // Get a reader capable of reading the response stream
                    using (var myStreamReader = new StreamReader(responseStream, Encoding.UTF8))
                    {
                        // Read stream content as string
                        var responseHtml = myStreamReader.ReadToEnd();
                        
                        // Assuming the response is in JSON format, deserialize it
                        // creating an instance of TData type (generic type declared before).
                        //data = JsonConvert.DeserializeObject<TData>(responseJSON);

                        //Console.WriteLine(responseHtml);
                        ViewData["html"] = responseHtml;
                        return View();
                    }
                }
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

rockstarmvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

rockstarmvc/Views/RockStar/Faith.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<img src="~/images/gm.jpg" alt="George Michael" class="img-responsive" />

<div>
<!-- Usage of azlyrics.com content by any third-party lyrics provider is prohibited by our licensing agreement. Sorry about that. -->
Well I guess it would be nice<br>
If I could touch your body<br>
I know not everybody<br>
Has got a body like you<br>
<br>
But I've got to think twice<br>
Before I give my heart away<br>
And I know all the games you play<br>
Because I play them too<br>
<br>
Oh but I<br>
Need some time off from that emotion<br>
Time to pick my heart up off the floor<br>
Oh when that love comes down<br>
Without devotion<br>
Well it takes a strong man baby<br>
But I'm showing you the door<br>
<br>
‘Cause I gotta have faith<br>
I gotta have faith<br>
‘Cause I gotta have faith, faith<br>
‘Cause I gotta have faith, faith, faith<br>
<br>
Baby,<br>
I know you're asking me to stay<br>
Say please, please, please don't go away<br>
You say I'm giving you the blues<br>
Maybe<br>
You mean every word you say<br>
Can't help but think of yesterday<br>
And another who tied me down to loverboy rules<br>
<br>
Before this river<br>
Becomes an ocean<br>
Before you throw my heart back on the floor<br>
Oh oh baby I reconsider<br>
My foolish notion<br>
Well I need someone to hold me<br>
But I'll wait for something more<br>
<br>
Yes I've gotta have faith…<br>
Mmm, I gotta have faith<br>
‘Cause I gotta have faith, faith, faith<br>
I gotta have faith-a-faith-a-faith<br>
<br>
Before this river<br>
Becomes an ocean<br>
Before you throw my heart back on the floor<br>
Oh oh baby I reconsider<br>
My foolish notion<br>
Well I need someone to hold me<br>
But I'll wait for something more<br>
<br>
Cause I gotta have faith<br>
Mmm I gotta have faith<br>
Because I got to have faith-a-faith-a-faith<br>
I gotta have faith-a-faith-a-faith
</div>

rockstarmvc/Views/RockStar/Faith2.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script>
        $(function () {
            $('#btn-all').on('click', function () {
                console.log("getting..");
                $.get(
                    'http://localhost:5000/rockstar/Faith',
                    function (response) {
                        console.log("> ", response);
                        $("#result").html(response);
                });
            });
        });
    </script>
</head>

<body>
    <img src="~/images/gm.jpg" alt="George Michael" class="img-responsive" />
    <button id="btn-all">Get Lyrics</button>
    <div id="result"></div>
</body>



rockstarmvc/Views/RockStar/Faith3.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
<style>
body {background-color: green;}
h1   {color: blue;}
p    {color: red;}
.myDiv {
  border: 5px outset red;
  background-color: lightblue;
  text-align: center;
}
</style>
</head>
<script>
    window.onload = function() {
        document.getElementById('myDiv2').innerHTML = '@ViewData["html"]'
    };
</script>
<body>

<div class="myDiv">
<pre>
  @ViewData["html"]
</pre>
</div>

<div id="myDiv2">Placeholder</div>

</body>
</html>

rockstarmvc/Views/RockStar/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>I'm a rock star!</h1>

rockstarmvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - rockstarmvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">rockstarmvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RockStar" asp-action="Index">My Music</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RockStar" asp-action="Faith">Faith</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RockStar" asp-action="Faith2">Faith2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RockStar" asp-action="Faith3">Faith3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - rockstarmvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>